import ajax from 'ic-ajax';

export default Ember.Object.extend({
	
	getHeaders : function(user)
	{
		var headers =
		{
			'X-REFSET-AUTH-TOKEN'		: user.token
		};

		return headers;
	}, 
	
	returnErrorResponse : function(response)
	{
		if (typeof response.jqXHR.responseJSON !== "undefined")
		{
			// We have an error generated by the API
			return {meta:response.jqXHR.responseJSON.meta};
		}
		else
		{
			// We've failed to speak to the API...
			return {meta:{errorInfo:{message:response.jqXHR.statusText,code:response.jqXHR.status.toString()}}};
		}
	},
	
	findList : function (user,idArray)
	{
		Ember.Logger.log("adapters.simple-members:findList");
		
		var jsonFormatIdArray = JSON.stringify(idArray);
		var _this = this;
	
		var result = ajax(RefsetENV.APP.conceptsApiBaseUrl, {headers:this.getHeaders(user), method:"post", data: jsonFormatIdArray, processData: false, contentType: 'application/json'}).then(function(response)
		{	
			return response;
		},
		function (response)
		{
			Ember.Logger.log("adapters.simple-members:findList error",response);
			return _this.returnErrorResponse(response);
		});

		return result;

	},
	
	find : function (user,id)
	{
		Ember.Logger.log("adapters.simple-members:find",user,id);
		var _this = this;
		
		var result = ajax(RefsetENV.APP.conceptsApiBaseUrl + '/' + id, {headers:this.getHeaders(user), method:"get"}).then(function(response)
		{	
			return response;
		},
		function (response)
		{
			Ember.Logger.log("adapters.simple-members:find error",response);
			return _this.returnErrorResponse(response);
		});

		return result;

	},

});