import ajax from 'ic-ajax';

export default Ember.Object.extend({
	
	getHeaders : function(user)
	{
		var headers =
		{
			'X-REFSET-PRE-AUTH-USERNAME'	: user.name,
			'X-REFSET-PRE-AUTH-TOKEN'		: user.token
		};

		return headers;
	}, 
	
	returnErrorResponse : function(response)
	{
		if (typeof response.jqXHR.responseJSON !== "undefined")
		{
			// We have an error generated by the API
			return {meta:response.jqXHR.responseJSON.meta};
		}
		else
		{
			// We've failed to speak to the API...
			return {meta:{errorInfo:{message:response.jqXHR.statusText,code:response.jqXHR.status.toString()}}};
		}
	},
	
	getComponentTypes : function (user)
	{
		Ember.Logger.log("adapters.type-lookups:getComponentTypes");
		var _this = this;
		
		var result = ajax(RefsetENV.APP.snomedTypesApiBaseUrl + 'componentTypes', {headers:this.getHeaders(user), method:"get"}).then(function(response)
		{	
			return response;
		},
		function (response)
		{
			Ember.Logger.log("adapters.type-lookups:getComponentTypes error",response);
			return _this.returnErrorResponse(response);
		});

		return result;
	},
	
	getModules : function (user)
	{
		Ember.Logger.log("adapters.type-lookups:getModules");
		var _this = this;
		
		var result = ajax(RefsetENV.APP.snomedTypesApiBaseUrl + 'modules', {headers:this.getHeaders(user), method:"get"}).then(function(response)
		{	
			return response;
		},
		function (response)
		{
			Ember.Logger.log("adapters.type-lookups:getModules error",response);
			return _this.returnErrorResponse(response);
		});

		return result;
	},

	getRefsetTypes : function (user)
	{
		Ember.Logger.log("adapters.type-lookups:getRefsetTypes");
		var _this = this;
		
		var result = ajax(RefsetENV.APP.snomedTypesApiBaseUrl + 'refsetTypes', {headers:this.getHeaders(user), method:"get"}).then(function(response)
		{	
			return response;
		},
		function (response)
		{
			Ember.Logger.log("adapters.type-lookups:getRefsetTypes error",response);
			return _this.returnErrorResponse(response);
		});

		return result;
	},
});