import ajax from 'ic-ajax';

export default Ember.Object.extend({

	returnErrorResponse : function(response)
	{
		if (typeof response.jqXHR.responseJSON !== "undefined")
		{
			// We have an error generated by the API
			return {meta:response.jqXHR.responseJSON.meta};
		}
		else
		{
			// We've failed to speak to the API...
			return {meta:{errorInfo:{message:response.jqXHR.statusText,code:response.jqXHR.status.toString()}}};
		}
	},
	
	getComponentTypes : function ()
	{
		Ember.Logger.log("adapters.type-lookups:getComponentTypes");
		var _this = this;
		
		var result = ajax(RefsetENV.APP.snomedTypesApiBaseUrl + 'componentTypes').then(function(response)
		{	
			return response;
		},
		function (response)
		{
			Ember.Logger.log("adapters.type-lookups:getComponentTypes error",response);
			return _this.returnErrorResponse(response);
		});

		return result;
	},
	
	getModules : function ()
	{
		Ember.Logger.log("adapters.type-lookups:getModules");
		var _this = this;
		
		var result = ajax(RefsetENV.APP.snomedTypesApiBaseUrl + 'modules').then(function(response)
		{	
			return response;
		},
		function (response)
		{
			Ember.Logger.log("adapters.type-lookups:getModules error",response);
			return _this.returnErrorResponse(response);
		});

		return result;
	},

	getRefsetTypes : function ()
	{
		Ember.Logger.log("adapters.type-lookups:getRefsetTypes");
		var _this = this;
		
		var result = ajax(RefsetENV.APP.snomedTypesApiBaseUrl + 'refsetTypes').then(function(response)
		{	
			return response;
		},
		function (response)
		{
			Ember.Logger.log("adapters.type-lookups:getRefsetTypes error",response);
			return _this.returnErrorResponse(response);
		});

		return result;
	},
});